const SET_MOVIE = 'SET_MOVIE'
const SET_TOTAL = 'SET_TOTAL'
const LOAD_MOVIE = 'LOAD_MOVIE'
const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE'
const LOAD_SELECTED_MOVIE = 'LOAD_SELECTED_MOVIE'
const SET_MOVIE_TRAILER = 'SET_MOVIE_TRAILER'
const MOVIE_TRAILER = 'MOVIE_TRAILER'
const SET_MOVIE_ACTORS = 'SET_MOVIE_ACTORS'
const MOVIE_ACTORS = 'MOVIE_ACTORS'
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_SEARCH = 'SET_SEARCH';
const SET_SEARCH_ACTIVE = 'SET_SEARCH_ACTIVE';

export {
    SET_MOVIE,
    SET_TOTAL,
    LOAD_MOVIE,
    SET_SELECTED_MOVIE,
    LOAD_SELECTED_MOVIE,
    MOVIE_TRAILER,
    SET_MOVIE_TRAILER,
    SET_MOVIE_ACTORS,
    MOVIE_ACTORS,
    SET_CURRENT_PAGE,
    SET_SEARCH,
    SET_SEARCH_ACTIVE,
}