const SIGN_UP = 'SIGN_UP'
const SIGN_UP_ACTIVATION = 'SIGN_UP_ACTIVATION'
const SIGN_IN = 'SIGN_IN'
const GET_USER = 'GET_USER'
const SET_USER = 'SET_USER'
const LOG_OUT = 'LOG_OUT'
const ACTIVATE = 'ACTIVATE';


export {
    SIGN_UP,
    SIGN_UP_ACTIVATION,
    SIGN_IN,
    GET_USER,
    SET_USER,
    LOG_OUT,
    ACTIVATE,
}